USE [sqlQLLSP] 
GO 
SET ANSI_NULLS ON 
GO 
SET QUOTED_IDENTIFIER ON 
GO 
CREATE TABLE [dbo].[CHITIETBANGLUONG]( 
	[THANG] [varchar](2) NOT NULL,
 	[MANV] [nvarchar](20) NOT NULL, 
	[MASP] [nvarchar](20) NOT NULL, 
	[SLSP] [nvarchar](6) NOT NULL,
	 CONSTRAINT CHITIETBANGLUONG_PK PRIMARY KEY (THANG, MANV,MASP)
)
GO 
 CREATE TABLE [dbo].[TAIKHOAN]( 
 	[TAIKHOAN] [nvarchar](20) NOT NULL, 
	[MATKHAU] [nvarchar](20) NOT NULL,
	 
	CONSTRAINT TAIKHOAN_PK PRIMARY KEY (TAIKHOAN)
);


GO 

CREATE TABLE [dbo].[LICHSU](
	[TAIKHOAN] [nvarchar](20) NOT NULL,
	[THOIGIAN] [nvarchar](20) NOT NULL,
	[NOIDUNG] [nvarchar](30) NOT NULL
);

GO
 CREATE TABLE [dbo].[TAIKHOANADM]( 
 	[TAIKHOANADM] [nvarchar](20) NOT NULL, 
	[MATKHAUADM] [nvarchar](20) NOT NULL, 
	CONSTRAINT TAIKHOANADM_PK PRIMARY KEY (TAIKHOANADM)
);

GO 
SET ANSI_NULLS ON 
GO 
SET QUOTED_IDENTIFIER ON 
 
GO 

CREATE TABLE [dbo].[BANGLUONG]( 
	[THANG] [varchar](2) NOT NULL,
 	[MANV] [nvarchar](20) NOT NULL, 
 	[TONGTIENLUONG] [nvarchar](30) NOT NULL 
	 CONSTRAINT BANGLUONG_PK PRIMARY KEY (THANG, MANV) 
);

GO 
/****** Object:  Table [dbo].[Student]    Script Date: 10/07/2019 20:59:08 ******/ SET ANSI_NULLS ON 
GO 
SET QUOTED_IDENTIFIER ON 
GO 
CREATE TABLE [dbo].[DMTinhluong]( 
 	[MASP] [nvarchar](20) NOT NULL, 
	[DONGIA] [nvarchar](30) NOT NULL, 
	CONSTRAINT DMTinhluong_PK PRIMARY KEY (MASP)
	); 
GO 
SET ANSI_NULLS ON 
GO 
SET QUOTED_IDENTIFIER ON 
GO 
CREATE TABLE [dbo].[PHONGBAN]( 
 	[MAPB] [nvarchar](20) NOT NULL, 
	[TENPB] [nvarchar](30) NOT NULL, 
	CONSTRAINT PHONGBAN_PK PRIMARY KEY (MAPB)
	); 
GO 
SET ANSI_NULLS ON 
GO 
SET QUOTED_IDENTIFIER ON 
GO 
CREATE TABLE [dbo].[NHANVIEN]( 
 	[MANV] [nvarchar](20) NOT NULL,  
	[TENNV] [nvarchar](30) NOT NULL, 
	[MUCLUONG] [nvarchar](30) NOT NULL, 
	[BACLUONG] [nvarchar](30) NOT NULL, 
	[MAPB] [nvarchar](20) NOT NULL,
	[PHAI] [nvarchar](5) NOT NULL,
	[NGAYSINH] [DateTime] NULL, 
	[DIACHI] [nvarchar](50) NOT NULL,
	[DIENTHOAI] [nvarchar](11) NOT NULL,
	[TRINHDOCM] [nvarchar](30) NOT NULL,
	[GHICHU] [nvarchar](50) NOT NULL,

	CONSTRAINT NHANVIEN_PK PRIMARY KEY (MANV) 
);
GO 
SET ANSI_NULLS ON 
GO 
SET QUOTED_IDENTIFIER ON 
GO 

SET ANSI_NULLS ON 
GO 
SET QUOTED_IDENTIFIER ON 
 
GO 
/****** Object:  ForeignKey [FK_Student_Faculty]    Script Date: 10/07/2019 20:59:08 ******/ 

ALTER TABLE CHITIETBANGLUONG
 ADD CONSTRAINT FK_CHITIETBANGLUONG_BANGLUONG
  FOREIGN KEY (THANG, MANV)
  REFERENCES BANGLUONG (THANG, MANV);
  GO

ALTER TABLE CHITIETBANGLUONG
 ADD CONSTRAINT FK_CHITIETBANGLUONG_DMTinhluong
  FOREIGN KEY (MASP)
  REFERENCES DMTinhluong (MASP);
  GO

ALTER TABLE NHANVIEN
 ADD CONSTRAINT FK_NHANVIEN_PHONGBAN
  FOREIGN KEY (MAPB)
  REFERENCES PHONGBAN (MAPB);
  GO

  ALTER TABLE CHITIETBANGLUONG
 ADD CONSTRAINT FK_CHITIETBANGLUONG_NHANVIEN
  FOREIGN KEY (MANV)
  REFERENCES NHANVIEN (MANV);
  GO


 SELECT * FROM TAIKHOANADM
 UNION ALL
  SELECT * FROM TAIKHOAN;


 ALTER TABLE TAIKHOANADM 
 ADD KIEMSOAT [NVARCHAR] (30)




  SELECT * FROM TAIKHOAN UNION ALL SELECT *FROM TAIKHOANADM;


    SELECT * FROM TAIKHOAN;
	SELECT *FROM TAIKHOANADM;


	select * from TAIKHOAN where TAIKHOAN = 'user1' and MATKHAU = 'deptrai'  UNION ALL select * from TAIKHOANADM where TAIKHOANADM = 'user1' and MATKHAUADM = 'deptrai' 
	select * from TAIKHOAN where TAIKHOAN = '" + tk + "' and MATKHAU = '" + mk + "' UNION ALL select * from TAIKHOANADM where TAIKHOANADM = '" + tk + "' and MATKHAUADM = '" + mk + "'


	select * from TAIKHOAN where TAIKHOAN = 'user1' and MATKHAU = 'KMWBYIP' UNION ALL select * from TAIKHOANADM where TAIKHOANADM = 'user1' and MATKHAUADM = 'KMWBYIP'

	select * from TAIKHOAN where TAIKHOAN = 'user1' and MATKHAU = 'KMWBYIP' and KIEMSOAT = 'bat' UNION ALL select * from TAIKHOANADM where TAIKHOANADM = 'user1' and MATKHAUADM = 'KMWBYIP' and KIEMSOAT = 'bat' 